{% set name = "recorder-napari" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/recOrder-napari-{{ version }}.tar.gz
  sha256: cb913dd8b223bd8a3b1e61282fbe03342c9b661a222b7c8f4c44740d4a25bac4

build:
  entry_points:
    - recorder = recOrder.scripts.cli:help
    - recorder.reconstruct = recOrder.scripts.cli:reconstruct
    - recorder.convert = recOrder.scripts.cli:convert
    - recOrder = recOrder.scripts.cli:help
    - recOrder.reconstruct = recOrder.scripts.cli:reconstruct
    - recOrder.convert = recOrder.scripts.cli:convert
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools-scm
  run:
    - click >=8.0.1
    - colorspacious >=1.1.2
    - importlib-metadata
    - matplotlib-base >=3.4.3
    - napari
    - napari-ome-zarr >=0.3.2
    - natsort >=7.1.1
    - numpy >=1.17.4
    - numpydoc
    - opencv >=4.5.3.56
    - psutil
    - packaging
    - pycromanager >=0.17
    - pyqtgraph >=0.12.3
    - python >=3.7
    - pywavelets >=1.1.1
    - pyyaml >=5.4.1
    - qtpy
    - scipy >=1.3.0
    - superqt >=0.2.4
    - tifffile
    - tqdm >=4.61.1
    - waveorder ==1.0.0rc0
    - zarr >=2.6.1

test:
  imports:
    - recOrder
    - recOrder.acq
    - recOrder.calib
    - recOrder.compute
    - recOrder.pipelines
    - recOrder.plugin
    - recOrder.scripts
    - recOrder.scripts.md5_check_sum
  commands:
    - pip list
    - pip check
    - recOrder --help
    - recOrder.reconstruct --help
    - recOrder.convert --help
    - recorder --help
    - recorder.reconstruct --help
    - recorder.convert --help
  requires:
    - pip

about:
  home: https://github.com/mehta-lab/recOrder
  summary: Computational microscopy toolkit for label-free imaging
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - mattersoflight
    - talonchandler
