{% set name = "recorder-napari" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/recOrder-napari-{{ version }}.tar.gz
  sha256: cb913dd8b223bd8a3b1e61282fbe03342c9b661a222b7c8f4c44740d4a25bac4

build:
  entry_points:
    - recorder = recOrder.scripts.cli:help
    - recorder.reconstruct = recOrder.scripts.cli:reconstruct
    - recorder.convert = recOrder.scripts.cli:convert
    - recOrder = recOrder.scripts.cli:help
    - recOrder.reconstruct = recOrder.scripts.cli:reconstruct
    - recOrder.convert = recOrder.scripts.cli:convert
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools-scm
  run:
    - click >=8.0.1
    - colorspacious >=1.1.2
    - importlib-metadata
    - matplotlib-base  # Imported but not in requirements
    - napari
    - napari-ome-zarr >=0.3.2
    - natsort >=7.1.1
    - numpy  # Imported but not in requirements
    - numpydoc  # Imported but not in requirements
    - psutil  # Imported but not in requirements
    - packaging  # Imported but not in requirements
    - pycromanager ==0.24.1
    - pyqtgraph >=0.12.3
    - python >=3.9
    - pyyaml  # Imported but not in requirements
    - qtpy  # Imported but not in requirements
    - scipy  # Imported but not in requirements
    - superqt  # Imported but not in requirements
    - tifffile  # Imported but not in requirements
    - waveorder ==1.0.0rc0  # Original package ==1.0.0rc0
    - zarr >=2.6.1  # Imported but not in requirements

test:
  imports:
    - recOrder
    - recOrder.acq
    - recOrder.calib
    - recOrder.compute
    - recOrder.io
    - recOrder.plugin
    - recOrder.scripts
    - recOrder.scripts.md5_check_sum
  commands:
    - pip list
    - pip check
    - recOrder --help
    - recOrder.reconstruct --help
    - recOrder.convert --help
    - recorder --help
    - recorder.reconstruct --help
    - recorder.convert --help
  requires:
    - pip

about:
  home: https://pypi.org/project/recorder
  summary: Computational microscopy toolkit for label-free imaging
  license: BSD-2-Clause
  license_file: LICENSE
  dev_url: https://github.com/mehta-lab/recOrder

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - mattersoflight
    - talonchandler
